name: bagged_pcmci
channels:
  - conda-forge
dependencies:
  - python[version='>=3.9']
  - scipy==1.8.0
  - numpy==1.21.5
  - numba==0.55.1
  - psutil
  - dcor
  - scikit-learn
  - networkx
  - gpytorch
  - statsmodels
  - matplotlib[version='>=3.4.0']
  - mpi4py
